### ISSUE TITLE
Failed to parse target (Datastore library has been updated)

### ISSUE THREAD

**Issue by danielmbarlow** [SingularitiesCR/datastore-emulator-docker#2]
We get this error when trying to connect to the emulator with the Datastore client library `"@google-cloud/datastore": "^5.0.3"` :

```
     Error: Failed to parse target ootravaux-integration_datastore_1:8081
      at Function.getDefaultAuthority (node_modules/@grpc/grpc-js/build/src/resolver-dns.js:257:15)
      at Object.getDefaultAuthority (node_modules/@grpc/grpc-js/build/src/resolver.js:73:32)
      at new ChannelImplementation (node_modules/@grpc/grpc-js/build/src/channel.js:89:48)
      at new Client (node_modules/@grpc/grpc-js/build/src/client.js:37:36)
      at new ServiceClientImpl (node_modules/@grpc/grpc-js/build/src/make-client.js:49:5)
      at GrpcClient.createStub (node_modules/google-gax/build/src/grpc.js:236:22)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
This might be caused by the move to gRPC on Google Cloud node.
https://github.com/googleapis/google-cloud-node/releases/tag/v0.30.0

Happily, with this version of GCloud SDK we don't have that issue any more:
```
Google Cloud SDK 274.0.1
alpha 2019.12.27
beta 2019.12.27
bq 2.0.51
cloud-datastore-emulator 2.1.0
```

However the Dockerfile in this project is based on `GCLOUD_SDK_VERSION=198.0.0-alpine`, so the emulator has surely been upgraded since that version. Could the GCloud SDK version be updated?

**Comment by danielmbarlow** [comment]
My bad. I think there was just trouble connecting to the emulator instance using a host name instead of an IP.
